env: standard
runtime: nodejs10
service: default
default_expiration: "0d 15m"

handlers:
  - url: /static
    static_dir: build/static
    secure: always

  - url: /img
    static_dir: build/img
    secure: always

  - url: /(.*\.(js))$
    static_files: build/\1
    upload: build/.*\.(js)$
    secure: always
    mime_type: application/javascript

  - url: /(.*\.(json|ico|js|png|txt))$
    static_files: build/\1
    upload: build/.*\.(json|ico|js|png|txt)$
    secure: always

  - url: .*
    static_files: build/index.html
    upload: build/index.html
    secure: always